# This is an example mods.toml file.
# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT" # Want to make your mod open source? Check out https://choosealicense.com/!

issueTrackerURL="https://github.com/robbert229/gtceu_extra"

[[mods]]
modId = "gtceu_extra"
# The version number of the mod - unlike in the Forge MDK,
# we'll use the processResources task to replace this for us
version = "${version}"
displayName = "GTCEu Extra Unofficial"
logoFile = "icon.png"

authors="John Rowley <john@johnrowley.co>"
# A multi-line description for your mod. This has no minimum length, but it *is* required!
description = "More Greg"

[[dependencies.gtceu_extra]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtceu_extra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtceu_extra]]
modId = "gtceu"
mandatory = true
versionRange = "[1.4.0,]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.gtceu_extra]]
modId = "tfc"
mandatory = true
versionRange = "[3.1.0-beta,)"
ordering = "AFTER"
side = "BOTH"